source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll"
# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed" # https://github.com/jekyll/jekyll-feed
  gem "jekyll-seo-tag" # https://jekyll.github.io/jekyll-seo-tag/
  gem "jekyll-archives" # https://github.com/jekyll/jekyll-archives
  gem "jekyll-diagrams" # https://github.com/zhustec/jekyll-diagrams
  gem "jekyll-sitemap" # https://github.com/jekyll/jekyll-sitemap
  gem "jekyll-compose" # https://github.com/jekyll/jekyll-compose  
  gem "jekyll-paginate-v2" # https://github.com/sverrirs/jekyll-paginate-v2
  gem "liquid_reading_time" # https://github.com/bdesham/reading_time
  gem "liquid_pluralize" # https://github.com/bdesham/pluralize

end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", :platforms => [:jruby]

gem "webrick"
